/**
 * @namespace Constants
 * @desc App constants
 */

/**
 * @constant {Object} ActionTypes
 * @memberof Constants
 */
export const ActionTypes = {
  GET_NOTES_REQUEST: "GET_NOTES_REQUEST",
  GET_NOTES_SUCCESS: "GET_NOTES_SUCCESS",
  GET_NOTES_FAILURE: "GET_NOTES_FAILURE",

  ADD_NOTE_REQUEST: "ADD_NOTE_REQUEST",
  ADD_NOTE_SUCCESS: "ADD_NOTE_SUCCESS",
  ADD_NOTE_FAILURE: "ADD_NOTE_FAILURE",

  EDIT_NOTE_REQUEST: "EDIT_NOTE_REQUEST",
  EDIT_NOTE_SUCCESS: "EDIT_NOTE_SUCCESS",
  EDIT_NOTE_FAILURE: "EDIT_NOTE_FAILURE",

  DELETE_NOTE_REQUEST: "DELETE_NOTE_REQUEST",
  DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
  DELETE_NOTE_FAILURE: "DELETE_NOTE_FAILURE",
};
